/nfs/scistore14/alistgrp/apanfero/CompressionEntropy/.conda/lib/python3.10/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(

Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.01it/s]
/nfs/scistore14/alistgrp/apanfero/CompressionEntropy/.conda/lib/python3.10/site-packages/datasets/load.py:1461: FutureWarning: The repository for togethercomputer/RedPajama-Data-1T-Sample contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/togethercomputer/RedPajama-Data-1T-Sample
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(
Starting ...
Ready.
  0%|                                                                                                                                                                                                                | 0/32 [00:00<?, ?it/s]
  0%|                                                                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]
0 self_attn.q_proj
Quantizing ...
time 2.65
error 386.066650390625
0 self_attn.k_proj
Quantizing ...
time 2.18
error 344.17425537109375
0 self_attn.v_proj
Quantizing ...
time 2.24
error 19.968936920166016
0 self_attn.o_proj
Quantizing ...
time 2.15
error 0.27071863412857056
0 mlp.gate_proj
Quantizing ...
time 2.52
error 104.43157196044922
0 mlp.up_proj
Quantizing ...
time 2.52
error 99.27603149414062
0 mlp.down_proj
Quantizing ...
time 6.21
Traceback (most recent call last):
  File "/nfs/scistore14/alistgrp/apanfero/CompressionEntropy/gptq/llama2.py", line 317, in <module>
    quantizers = llama_sequential(model, dataloader, DEV)
  File "/nfs/scistore14/alistgrp/apanfero/CompressionEntropy/.conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/nfs/scistore14/alistgrp/apanfero/CompressionEntropy/gptq/llama2.py", line 136, in llama_sequential
    mse += torch.nn.functional(outs[j][0], out).item()
TypeError: 'module' object is not callable