/nfs/scistore14/alistgrp/apanfero/CompressionEntropy/.conda/lib/python3.10/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.15it/s]
/nfs/scistore14/alistgrp/apanfero/CompressionEntropy/.conda/lib/python3.10/site-packages/datasets/load.py:1461: FutureWarning: The repository for togethercomputer/RedPajama-Data-1T-Sample contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/togethercomputer/RedPajama-Data-1T-Sample
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(
  0%|                                                                                                                                                                                                                 | 0/32 [00:00<?, ?it/s]
  0%|                                                                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]
Starting ...

  assignments = torch.bucketize(weight, boundaries[bits])                                                                                                                                                              | 0/1 [00:00<?, ?it/s]
0 self_attn.q_proj
Quantizing ...
time 1.31
error 298259.3125
0 self_attn.k_proj
Quantizing ...
time 0.85
error 301271.0625
0 self_attn.v_proj
Quantizing ...
time 0.86
error 293381.9375
0 self_attn.o_proj
Quantizing ...
time 0.86
error 5666.4873046875
0 mlp.gate_proj
Quantizing ...
time 0.87
error 1242572.375
0 mlp.up_proj
Quantizing ...
time 0.87
error 1241758.25
0 mlp.down_proj
Quantizing ...
  0%|                                                                                                                                                                                                                 | 0/32 [00:15<?, ?it/s]
Traceback (most recent call last):
  File "/nfs/scistore14/alistgrp/apanfero/CompressionEntropy/gptq/llama2.py", line 336, in <module>
    quantizers = llama_sequential(model, dataloader, DEV)
  File "/nfs/scistore14/alistgrp/apanfero/CompressionEntropy/.conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/nfs/scistore14/alistgrp/apanfero/CompressionEntropy/gptq/llama2.py", line 133, in llama_sequential
    res = gptq[name].fasterquant(
  File "/nfs/scistore14/alistgrp/apanfero/CompressionEntropy/gptq/gptq.py", line 168, in fasterquant
    self.layer.weight = torch.nn.Parameter(Q.reshape(self.layer.weight.shape).to(self.layer.weight.data.dtype), requires_grad=False)
RuntimeError: shape '[4096, 11008]' is invalid for input of size 46137344
time 2.52
error 9308.83984375